apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-demo
spec:
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - image: yangmv/flask-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: flask-demo
        ports:
        - containerPort: 5000
          name: web
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: flask-demo
  labels:
    app: flask-demo
spec:
  selector:
    app: flask-demo
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000