apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-demo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: flask-demo.yangmv.com
    http:
      paths:
      - path:
        backend:
          serviceName: flask-demo
          servicePort: 5000