apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: yangmv/flask-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000


---
#apiVersion: v1
#kind: Service
#metadata:
#  name: flask-demo
#  labels:
#    app: flask-demo
#spec:
#  selector:
#    app: flask-demo
#  type: NodePort
#  ports:
#  - name: http
#    port: 5000
#    targetPort: 5000